# Generated by Django 2.1.7 on 2021-02-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20210202_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='budget_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costCategory', models.CharField(max_length=50)),
                ('budgetYear', models.PositiveSmallIntegerField()),
                ('budgetAmount', models.FloatField()),
                ('executionAmount', models.FloatField()),
                ('executionRate', models.FloatField()),
            ],
        ),
    ]
