# Generated by Django 2.1.7 on 2021-02-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_authbuy_departmentexes_emergencyfund_headbuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_all',
            name='operating',
            field=models.TextField(blank=True, default='操作明细'),
        ),
        migrations.AddField(
            model_name='budget_all',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
