# Generated by Django 2.1.7 on 2021-02-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20210203_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='authbuy',
            name='assetType',
            field=models.CharField(default='笔记本电脑', max_length=50, verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='authbuy',
            name='status',
            field=models.CharField(choices=[('yes', '已完成'), ('ing', '采购中'), ('no', '取消')], default='no', max_length=50, verbose_name='设备类型'),
        ),
    ]
